apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: hello-app
  namespace: fleet-default
spec:
  branch: main
  insecureSkipTLSVerify: false
  paths:
    - /live
  repo: https://github.com/mak3r/fleet-demo-src
  targets:
    - clusterSelector:
        matchExpressions:
          - key: provider.cattle.io
            operator: NotIn
            values:
              - harvester
