apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: jfk-cluster-config
  namespace: fleet-local
spec:
  branch: main
  paths:
    - /airports/jfk/
  repo: https://github.com/mak3r/fleet-downstream-clusters
  targets:
    - clusterSelector:
        matchExpressions:
          - key: provider.cattle.io
            operator: NotIn
            values:
              - harvester