apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventorySelectorTemplate
metadata:
  name: muc-machine-selector
  namespace: fleet-default
spec:
  template:
    spec:
      selector:
        matchExpressions:
          - key: location
            operator: In
            values: [ 'de' ]
---
kind: Cluster
apiVersion: provisioning.cattle.io/v1
metadata:
  name: muc
  namespace: fleet-default
  labels:
    environment: demo
    edge-arch: single-node
    corp: suse
    location: de
spec:
  rkeConfig:
    machinePools:
      - controlPlaneRole: true
        etcdRole: true
        machineConfigRef:
          apiVersion: elemental.cattle.io/v1beta1
          kind: MachineInventorySelectorTemplate
          name: muc-machine-selector
        name: pool1
        quantity: 1
        unhealthyNodeTimeout: 0s
        workerRole: true
  kubernetesVersion: v1.25.8+k3s1
