apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventorySelectorTemplate
metadata:
  name: jfk-machine-selector
  namespace: fleet-default
spec:
  template:
    spec:
      selector:
        matchExpressions:
          - key: location
            operator: In
            values: [ 'us' ]
---
kind: Cluster
apiVersion: provisioning.cattle.io/v1
metadata:
  name: jfk
  namespace: fleet-default
  labels:
    environment: vm
    edge-arch: single-node
    region: new-york-area
    airport: jfk
    geo: ny
    demo: false
    managed: true
spec:
  rkeConfig:
    machinePools:
      - controlPlaneRole: true
        etcdRole: true
        workerRole: true
        machineConfigRef:
          apiVersion: elemental.cattle.io/v1beta1
          kind: MachineInventorySelectorTemplate
          name: jfk-machine-selector
        name: pool1
        quantity: 1
        unhealthyNodeTimeout: 0s
  kubernetesVersion: v1.23.7+k3s1
